export const TRANSACTION_CREATED = 'CREATED';
export const TRANSACTION_PENDING = 'PENDING';
export const TRANSACTION_CANCELLED = 'CANCELED';
export const TRANSACTION_CONFIRMED = 'CONFIRMED';
export const TRANSACTION_DISPUTED = 'DISPUTED';
