# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#platform :ios, '8.0'

target 'GAMember' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GAMember
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge', # Include this for RN >= 0.47
        'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket', # Needed for debugging
        'RCTAnimation', # Needed for FlatList and animations running on native UI thread
        # Add any other subspecs you want to use in your project
      ]
      # Explicitly include Yoga if you are using RN >= 0.42.0
      pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
    pod 'Firebase/Database', '~> 5.15.0'
    pod 'Firebase/Messaging', '~> 5.15.0'
    pod 'GoogleSignIn', '~> 4.4.0'

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  #pod 'react-native-battery', :path => '../node_modules/react-native-battery'

  #pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'


  #pod 'RNSVG', :path => '../node_modules/react-native-svg'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
end



