# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#platform :ios, '8.0'

target 'GAMember' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GAMember
    #pod 'React', :path => '../node_modules/react-native'
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
    pod 'Firebase/Database', '~> 5.15.0'
    pod 'Firebase/Messaging', '~> 5.15.0'
    pod 'GoogleSignIn', '~> 4.4.0'


    #pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  #pod 'react-native-battery', :path => '../node_modules/react-native-battery'

  #pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'


end


